language: node_js

node_js:
    - "node"

cache:
    directories:
        - node_modules

script: "npm run ci"

env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
